# Taps
tap "hashicorp/tap"
tap "homebrew/services"
tap "max-sixty/worktrunk"
tap "nikitabobko/tap"
tap "rjcoelho/boneyard"

# Previously managed by nix (home.nix packages)
brew "neovim"
brew "go"
brew "tmux"
brew "solidity"

# Formulae (from `brew leaves`)
brew "awscli"
brew "bash"
brew "bat"
brew "cargo-nextest"
brew "clip"
brew "coreutils"
brew "croc"
brew "dnsmasq"
brew "docutils"
brew "duti"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-gui"
brew "git-lfs"
brew "gnupg"
brew "gobject-introspection"
brew "graphviz"
brew "grpcurl"
brew "guile"
brew "hey"
brew "ipget"
brew "jd"
brew "jq"
brew "k6"
brew "max-sixty/worktrunk/wt"
brew "mkcert"
brew "mtr"
brew "nnn"
brew "pipx"
brew "protoc-gen-go"
brew "protoc-gen-go-grpc"
brew "python@3.10"
brew "python@3.11"
brew "python@3.9"
brew "ripgrep"
brew "snappy"
brew "sphinx-doc"
brew "starship"
brew "stow"
brew "vegeta"
brew "xclip"
brew "yq"
brew "zoxide"
brew "zplug"

# Tooling for this repo
brew "chezmoi"

# Casks
cask "alt-tab"
cask "ghostty"
