# Taps
tap "hashicorp/tap"
tap "homebrew/services"
tap "nikitabobko/tap"
tap "rjcoelho/boneyard"

# Formulae (from `brew leaves`)
brew "bash"
brew "clip"
brew "coreutils"
brew "dnsmasq"
brew "docutils"
brew "duti"
brew "ffmpeg"
brew "git"
brew "git-gui"
brew "git-lfs"
brew "gnupg"
brew "gobject-introspection"
brew "graphviz"
brew "guile"
brew "mtr"
brew "nnn"
brew "snappy"
brew "sphinx-doc"
brew "stow"
brew "xclip"
brew "zplug"

# Casks
cask "alt-tab"
cask "ghostty"
