add_newline = false
format = "$hostname$directory$git_branch$character"

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "bold yellow"

[directory]
format = "[$path]($style)"
style = "bold blue"
truncation_length = 3
truncation_symbol = "../"
truncate_to_repo = false

[git_branch]
symbol = ""
format = " [($branch)]($style)"
style = "cyan"

[character]
format = " $symbol "
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
